#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_MYSTERY_ZONE   (0 | (0 << 8))

#define MAP_GROUPS_COUNT 1

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
